name = "OrdinaryDiffEq"
uuid = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>", "Yingbo Ma <mayingbo5@gmail.com>"]
version = "7.0.0-DEV"

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
OrdinaryDiffEqBDF = "6ad6398a-0878-4a85-9266-38940aa047c8"
OrdinaryDiffEqCore = "bbf590c4-e513-4bbe-9b18-05decba2e5d8"
OrdinaryDiffEqDefault = "50262376-6c5a-4cf5-baba-aaf4f84d72d7"
OrdinaryDiffEqRosenbrock = "43230ef6-c299-4910-a778-202eb28ce4ce"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
OrdinaryDiffEqVerner = "79d7bb75-1356-48c1-b8c0-6832512096c2"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[sources]
OrdinaryDiffEqBDF = {path = "lib/OrdinaryDiffEqBDF"}
OrdinaryDiffEqCore = {path = "lib/OrdinaryDiffEqCore"}
OrdinaryDiffEqDefault = {path = "lib/OrdinaryDiffEqDefault"}
OrdinaryDiffEqRosenbrock = {path = "lib/OrdinaryDiffEqRosenbrock"}
OrdinaryDiffEqTsit5 = {path = "lib/OrdinaryDiffEqTsit5"}
OrdinaryDiffEqVerner = {path = "lib/OrdinaryDiffEqVerner"}

[compat]
ADTypes = "1.10"
CommonSolve = "0.2.4"
DocStringExtensions = "0.9.5"
OrdinaryDiffEqBDF = "1.16.0"
OrdinaryDiffEqCore = "3"
OrdinaryDiffEqDefault = "1.7.0"
OrdinaryDiffEqRosenbrock = "1.15.1"
OrdinaryDiffEqTsit5 = "1.4.0"
OrdinaryDiffEqVerner = "1.5.0"
SciMLBase = "2.143"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[targets]
test = ["Test", "SafeTestsets", "Pkg"]
