using OrdinaryDiffEqSDC
using OrdinaryDiffEqSDC: SDCTableau, sdc_qdelta_for, min_sr_s_coefficients,
    SDC_DIAGONAL_SWEEPERS
using LinearAlgebra
using Test

# Diagonal entries generated by qmat, which is the reference implementation for
# these coefficients. MIN-SR-FLEX is listed sweep by sweep; the entry past sweep
# M is the MIN-SR-S fallback.
const FLEX_RADAU_RIGHT_3 = [
    [0.155051025722, 0.644948974278, 1.0],
    [0.0775255128608, 0.322474487139, 0.5],
    [0.0516836752406, 0.214982991426, 0.333333333333],
    [0.10404994025, 0.332812745429, 0.48129014021],
]
const FLEX_LOBATTO_4 = [
    [0.0, 0.27639320225, 0.72360679775, 1.0],
    [0.0, 0.138196601125, 0.361803398875, 0.5],
    [0.0, 0.0921310674167, 0.241202265917, 0.333333333333],
    [0.0, 0.0690983005625, 0.180901699437, 0.25],
    [0.0, 0.10443338887, 0.244534313514, 0.326316905664],
]

@testset "MIN-SR coefficients match qmat" begin
    @test min_sr_s_coefficients(SDCNodes.Legendre, SDCQuadrature.RadauRight, 4) ≈
        [0.053635876650205347, 0.182977275269505, 0.31493338359264461, 0.38516735854603845] atol = 1.0e-13

    tab = SDCTableau(
        Float64, 3, SDCNodes.Legendre, SDCQuadrature.RadauRight,
        SDCSweeper.MIN_SR_FLEX, 4
    )
    for (k, expected) in enumerate(FLEX_RADAU_RIGHT_3)
        @test diag(sdc_qdelta_for(tab, k)) ≈ expected atol = 1.0e-11
    end

    tab = SDCTableau(
        Float64, 4, SDCNodes.Legendre, SDCQuadrature.Lobatto, SDCSweeper.MIN_SR_FLEX, 5
    )
    for (k, expected) in enumerate(FLEX_LOBATTO_4)
        @test diag(sdc_qdelta_for(tab, k)) ≈ expected atol = 1.0e-11
    end
end

@testset "MIN-SR sweepers have the property they are defined by" begin
    for quad_type in (SDCQuadrature.Gauss, SDCQuadrature.RadauRight), M in 2:6
        Q = SDCTableau(Float64, M, SDCNodes.Legendre, quad_type, SDCSweeper.BE).Q
        τ = SDCTableau(Float64, M, SDCNodes.Legendre, quad_type, SDCSweeper.BE).nodes

        # Čaklović et al. Theorem 2.8: diag(τ)/M makes the non-stiff iteration
        # matrix Q - QΔ nilpotent of index M.
        ns = first(
            SDCTableau(Float64, M, SDCNodes.Legendre, quad_type, SDCSweeper.MIN_SR_NS).QΔ
        )
        @test diag(ns) ≈ τ ./ M
        @test maximum(abs, (Q - ns)^M) < 1.0e-11

        # Definition 2.11: the stiff-limit iteration matrix I - QΔ⁻¹Q is driven
        # towards nilpotency instead, so its spectral radius is near zero. The
        # tabulated solve is numerical, and the residual grows with M.
        s = first(
            SDCTableau(Float64, M, SDCNodes.Legendre, quad_type, SDCSweeper.MIN_SR_S).QΔ
        )
        @test maximum(abs, eigvals(I - inv(s) * Q)) < 1.0e-2

        # Theorem 2.13: the product of the stiff-limit iteration matrices over
        # sweeps 1…M vanishes for diag(τ)/k.
        flex = SDCTableau(
            Float64, M, SDCNodes.Legendre, quad_type, SDCSweeper.MIN_SR_FLEX, M
        )
        product = prod(
            I - inv(sdc_qdelta_for(flex, k)) * Q for k in M:-1:1
        )
        @test maximum(abs, product) < 1.0e-8
    end
end

@testset "MIN-SR sweepers are diagonal and sweep dependent where advertised" begin
    for sweeper in (SDCSweeper.MIN_SR_NS, SDCSweeper.MIN_SR_S, SDCSweeper.MIN_SR_FLEX)
        @test sweeper in SDC_DIAGONAL_SWEEPERS
        tab = SDCTableau(
            Float64, 4, SDCNodes.Legendre, SDCQuadrature.RadauRight, sweeper, 3
        )
        @test all(Q -> Q ≈ Diagonal(Q), tab.QΔ)
    end
    # Only MIN-SR-FLEX changes from sweep to sweep.
    flex = SDCTableau(
        Float64, 4, SDCNodes.Legendre, SDCQuadrature.RadauRight, SDCSweeper.MIN_SR_FLEX, 3
    )
    @test sdc_qdelta_for(flex, 1) != sdc_qdelta_for(flex, 2)
    @test sdc_qdelta_for(flex, 2) != sdc_qdelta_for(flex, 3)
    @test allunique(flex.QΔ)
    static = SDCTableau(
        Float64, 4, SDCNodes.Legendre, SDCQuadrature.RadauRight, SDCSweeper.MIN_SR_S, 3
    )
    # One entry serving every sweep, so the accessor returns the same object.
    @test sdc_qdelta_for(static, 1) === sdc_qdelta_for(static, 7)
end

@testset "MIN-SR-S reports missing table entries" begin
    @test_throws ArgumentError min_sr_s_coefficients(
        SDCNodes.Legendre, SDCQuadrature.RadauRight, 25
    )
end

@testset "diagonal sweepers on a stiff problem" begin
    # Prothero-Robinson: exact solution cos(t) for every lambda.
    prob = ODEProblem((u, p, t) -> -1.0e4 * (u - cos(t)) - sin(t), 1.0, (0.0, 1.0))
    stiff_error(sweeper, K) = begin
        sol = solve(
            prob, SDC(num_nodes = 3, num_sweeps = K, sweeper = sweeper);
            dt = 0.1, adaptive = false, save_everystep = true, dense = false
        )
        maximum(abs(u - cos(t)) for (u, t) in zip(sol.u, sol.t))
    end

    # The point of MIN-SR-S: once the iteration has had enough sweeps it matches
    # the serial LU sweeper while still decoupling across the nodes.
    @test stiff_error(SDCSweeper.MIN_SR_S, 8) < 10 * stiff_error(SDCSweeper.LU, 8)

    # And it is far better than the naive diagonal choice, which never gets there.
    @test stiff_error(SDCSweeper.MIN_SR_S, 8) < stiff_error(SDCSweeper.BEpar, 8) / 1.0e6

    # MIN-SR-NS is optimised for the non-stiff limit and is not A-stable, so it
    # is expected to diverge here. Asserting that keeps the distinction honest.
    @test !(stiff_error(SDCSweeper.MIN_SR_NS, 3) < 1)
end
