name: IntegrationTest
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: ${{ matrix.package.repo }}/${{ matrix.package.group }}/1
    strategy:
      fail-fast: false
      matrix:
        package:
          - {user: SciML, repo: DiffEqCallbacks.jl, group: All}
          - {user: SciML, repo: SciMLSensitivity.jl, group: Core1}
          - {user: SciML, repo: SciMLSensitivity.jl, group: Core2}
          - {user: SciML, repo: SciMLSensitivity.jl, group: Core3}
          - {user: SciML, repo: SciMLSensitivity.jl, group: Core4}
          - {user: SciML, repo: SciMLSensitivity.jl, group: Core5}
          - {user: SciML, repo: ModelingToolkit.jl, group: InterfaceI}
          - {user: SciML, repo: ModelingToolkit.jl, group: InterfaceII}
          - {user: SciML, repo: ModelingToolkit.jl, group: Initialization}
          - {user: SciML, repo: ModelingToolkit.jl, group: SymbolicIndexingInterface}
          - {user: nathanaelbosch, repo: ProbNumDiffEq.jl, group: Downstream}
          - {user: SKopecz, repo: PositiveIntegrators.jl, group: Downstream}
    uses: "SciML/.github/.github/workflows/downstream.yml@v1"
    with:
      owner: "${{ matrix.package.user }}"
      repo: "${{ matrix.package.repo }}"
      upstream-subdirs: ".,lib/*"
      group: "${{ matrix.package.group }}"
      julia-version: "1"
    secrets: "inherit"
